# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Brunch.gitlab-ci.yml
# Full project: https://gitlab.com/pages/brunch
image: node:latest
pages:
  cache:
    paths:
      - node_modules/
  script:
    - ls
    # - npm run build
    # - rm -rf public
    # - mkdir public
    # - cp -r dist/* public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production

